#!/usr/bin/env bash
# Writes ios/Trial.xcconfig from ~/.kvitta-trial-key so the built app carries the hosted
# server's trial key (KvittaTrialKey in the Info.plist). Without the key file it writes an
# empty config, which builds an app that asks for the key in Jag → Utvecklarverktyg instead.
# Run before xcodegen; trial.sh does. Never commit the result — the repo is public.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
key_file="${KVITTA_TRIAL_KEY_FILE:-$HOME/.kvitta-trial-key}"
out="$root/ios/Trial.xcconfig"
if [ -s "$key_file" ]; then
  printf '// Generated by tools/trial-config.sh — gitignored.\nKVITTA_TRIAL_KEY = %s\n' "$(tr -d '[:space:]' < "$key_file")" > "$out"
  echo "ios/Trial.xcconfig: nyckel från $key_file"
else
  printf '// Generated by tools/trial-config.sh — gitignored. No key file at %s.\nKVITTA_TRIAL_KEY =\n' "$key_file" > "$out"
  echo "ios/Trial.xcconfig: tom (ingen $key_file)"
fi
